version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
